name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel twine build

    - name: Build wheel
      run: |
        python -m build
        echo "wheel file is created"
    - name: Publish to PyPI
#      if: github.event_name == 'push' && github.event_ref == 'refs/heads/master'
      run: |
        echo "Deploying to PyPI..."
        python -m twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*

